### ISSUE TITLE
🎚 Supported Devices

### ISSUE THREAD

**Issue by bwp91** [donavanbecker/homebridge-meross#300]
The list of supported devices has moved to the wiki.

If you have a device to add to the list please comment on this thread!

**Comment by rcoletti116** [comment]
MSS630 working with local. Didn’t test cloud.

**Comment by CocoaBob** [comment]
About MSG100, I didn't check the source code, just please make sure when **messageId, timestamp, sign** are empty, the plugin should still consider it's a valid settings.

Now after configuring the key and uuid (serial number), after relaunching Homebridge, I got this error
```
MSG100 could not be initialised as Cannot read property 'ObstructionDetected' of undefined at new deviceLocalGarage (/usr/lib/node_modules/homebridge-meross/lib/device/local/garage.js:60:65)
```
Then I go to HomeKit, when I tap the garage door in HomeKit, another error appears
```
sending update failed as Cannot read property 'CurrentDoorState' of undefined at /usr/lib/node_modules/homebridge-meross/lib/device/local/garage.js:92:76
```

Ok, just checked a little bit of the codes, for MSG100, we need the `payload`, with device uuid, let me copy & paste the correct JSON formats here (copied from my Postman collection). I will delete this comment when you guys get the content.

Open Door
```
{
  "payload" : {
    "state" : {
      "channel" : 0,
      "open" : 1,
      "uuid" : "{{device_uuid}}"
    }
  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "SET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.GarageDoor.State",
    "uuid" : "{{device_uuid}}",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}
```

Close Door
```
{
  "payload" : {
    "state" : {
      "channel" : 0,
      "open" : 0,
      "uuid" : "{{device_uuid}}"
    }
  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "SET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.GarageDoor.State",
    "uuid" : "{{device_uuid}}",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}
```

Get Status
```
{
  "payload" : {
    "state" : {
      "channel" : 0
    }
  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "GET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.GarageDoor.State",
    "uuid" : "{{device_uuid}}",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}
```

Get Timer X (I don't think we need it)
```
{
  "payload" : {

  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "GET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.Digest.TimerX",
    "uuid" : "{{device_uuid}}",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}
```

Get Trigger X (I don't think we need it)
```
{
  "payload" : {

  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "GET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.Digest.TriggerX",
    "uuid" : "{{device_uuid}}",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOSLocal",
    "payloadVersion" : 1
  }
}
```

Get Online Status (check if the device is accessible?)
```
{
  "payload" : {

  },
  "header" : {
    "messageId" : "{{messageId}}",
    "method" : "GET",
    "from" : "http:\/\/{{device_ip}}\/config",
    "timestamp" : {{timestamp}},
    "namespace" : "Appliance.System.Online",
    "sign" : "{{sign}}",
    "triggerSrc" : "iOS",
    "payloadVersion" : 1
  }
}
```

**Comment by CocoaBob** [comment]
Seems nothing happens if I tap `ADD CLOUD DEVICE SETTINGS` or click on the textfields (can't choose or write anything)
 
![image](https://user-images.githubusercontent.com/489666/126919699-18f41740-f2b2-4cab-8684-5ebf28363fd3.png)

**Comment by donavanbecker** [comment]
@CocoaBob do you have a key or both your username and password filed in for your account? if you don't then it won't let you add cloud settings.

**Comment by CocoaBob** [comment]
@donavanbecker  Hello, long time no see! I only added my key
![image](https://user-images.githubusercontent.com/489666/126987443-4df3aa9a-58fb-405f-a1eb-6a542c6b06ce.png)

**Comment by CocoaBob** [comment]
OK, I see what you meant, I need the username and password 😅 I think the UX could be optimized.

**Comment by CocoaBob** [comment]
@donavanbecker Just tried username and password, I have 2 MSG100, one supports HomeKit, one doesn't.
Here are the errors I got from Homebridge logs.
```
MSG100_WiFi_Version is currently not supported, do create a github issue https://git.io/JtfVC with info:
Jul 26 13:31:49 PiServer homebridge[15850]: {
Jul 26 13:31:49 PiServer homebridge[15850]:   uuid: '__DEVICE_UUID__',
Jul 26 13:31:49 PiServer homebridge[15850]:   onlineStatus: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   devName: 'MSG100_WiFi_Version',
Jul 26 13:31:49 PiServer homebridge[15850]:   devIconId: 'device039_un',
Jul 26 13:31:49 PiServer homebridge[15850]:   bindTime: 1592019760,
Jul 26 13:31:49 PiServer homebridge[15850]:   deviceType: 'MSG100',
Jul 26 13:31:49 PiServer homebridge[15850]:   subType: 'us',
Jul 26 13:31:49 PiServer homebridge[15850]:   channels: [Array],
Jul 26 13:31:49 PiServer homebridge[15850]:   region: 'us',
Jul 26 13:31:49 PiServer homebridge[15850]:   fmwareVersion: '3.2.3',
Jul 26 13:31:49 PiServer homebridge[15850]:   hdwareVersion: '3.0.0',
Jul 26 13:31:49 PiServer homebridge[15850]:   userDevIcon: '',
Jul 26 13:31:49 PiServer homebridge[15850]:   iconType: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   skillNumber: '',
Jul 26 13:31:49 PiServer homebridge[15850]:   cluster: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   domain: 'mqtt-us.meross.com',
Jul 26 13:31:49 PiServer homebridge[15850]:   reservedDomain: 'mqtt-us.meross.com'
Jul 26 13:31:49 PiServer homebridge[15850]: }
```
```
MSG100_HomeKit_Version is currently not supported, do create a github issue https://git.io/JtfVC with info:
Jul 26 13:31:49 PiServer homebridge[15850]: {
Jul 26 13:31:49 PiServer homebridge[15850]:   uuid: '__DEVICE_UUID__',
Jul 26 13:31:49 PiServer homebridge[15850]:   onlineStatus: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   devName: 'MSG100_HomeKit_Version',
Jul 26 13:31:49 PiServer homebridge[15850]:   devIconId: 'device039_un',
Jul 26 13:31:49 PiServer homebridge[15850]:   bindTime: 1619285890,
Jul 26 13:31:49 PiServer homebridge[15850]:   deviceType: 'MSG100',
Jul 26 13:31:49 PiServer homebridge[15850]:   subType: 'us',
Jul 26 13:31:49 PiServer homebridge[15850]:   channels: [Array],
Jul 26 13:31:49 PiServer homebridge[15850]:   region: 'us',
Jul 26 13:31:49 PiServer homebridge[15850]:   fmwareVersion: '4.1.14',
Jul 26 13:31:49 PiServer homebridge[15850]:   hdwareVersion: '4.0.0',
Jul 26 13:31:49 PiServer homebridge[15850]:   userDevIcon: '',
Jul 26 13:31:49 PiServer homebridge[15850]:   iconType: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   skillNumber: '3',
Jul 26 13:31:49 PiServer homebridge[15850]:   cluster: 1,
Jul 26 13:31:49 PiServer homebridge[15850]:   domain: 'mqtt-us.meross.com',
Jul 26 13:31:49 PiServer homebridge[15850]:   reservedDomain: 'mqtt-us.meross.com'
Jul 26 13:31:49 PiServer homebridge[15850]: }
```

And here's my configuration
![image](https://user-images.githubusercontent.com/489666/127033485-84857e09-7dfa-4c3a-a25a-e01089a88352.png)

**Comment by bwp91** [comment]
The MSG100 isn't supported via the cloud yet.

Please update to the new beta.5, (the config layout has changed again), in the Device Settings section for your garage device, set the 'Connection' to 'Local'.

**Comment by app-ch** [comment]
with option local in the new beta the device seems not supported.

[7/27/2021, 5:57:25 AM] [Meross] [Garage] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"name":"Garage","serialNumber":"2103xxxxxxxxxxxxx","connection":"local","model":"MSG100","deviceUrl":"192.168.xxx.xxx","garageDoorOpeningTime":15,"uuid":"2103xxxxxxxxxxxxx","deviceType":"MSG100","devName":"Garage","channels":[],"hbDeviceId":"2103xxxxxxxxxxxxx"}

**Comment by bwp91** [comment]
> with option local in the new beta the device seems not supported.
> 
> [7/27/2021, 5:57:25 AM] [Meross] [Garage] is currently not supported, do create a github issue https://git.io/JtfVC with info:
> {"name":"Garage","serialNumber":"2103xxxxxxxxxxxxx","connection":"local","model":"MSG100","deviceUrl":"192.168.xxx.xxx","garageDoorOpeningTime":15,"uuid":"2103xxxxxxxxxxxxx","deviceType":"MSG100","devName":"Garage","channels":[],"hbDeviceId":"2103xxxxxxxxxxxxx"}

@app-ch 

Please try beta.7

It's an attempt to copy the protocol used for local control.

If something isn't working, please make sure plugin debug logging is ON and reply with logs if appropriate.

Thanks

**Comment by app-ch** [comment]
> > with option local in the new beta the device seems not supported.
> > [7/27/2021, 5:57:25 AM] [Meross] [Garage] is currently not supported, do create a github issue https://git.io/JtfVC with info:
> > {"name":"Garage","serialNumber":"2103xxxxxxxxxxxxx","connection":"local","model":"MSG100","deviceUrl":"192.168.xxx.xxx","garageDoorOpeningTime":15,"uuid":"2103xxxxxxxxxxxxx","deviceType":"MSG100","devName":"Garage","channels":[],"hbDeviceId":"2103xxxxxxxxxxxxx"}
> 
> @app-ch
> 
> Please try beta.7
> 
> It's an attempt to copy the protocol used for local control.
> 
> If something isn't working, please make sure plugin debug logging is ON and reply with logs if appropriate.
> 
> Thanks

In Beta 7 it is now working fine!

**Comment by bwp91** [comment]
> In Beta 7 it is now working fine!

Fab.

Can you do me a favour - control the garage from the meross app, and in the logs should appear a message like:

```
[device] incoming cloud mqtt message %%%%%%
[device] real-time garage cloud updates not supported
[device] please post the above message in a github issue
```

Can you find these lines and post them here?

**Comment by app-ch** [comment]
> > In Beta 7 it is now working fine!
> 
> Fab.
> 
> Can you do me a favour - control the garage from the meross app, and in the logs should appear a message like:
> 
> ```
> [device] incoming cloud mqtt message %%%%%%
> [device] real-time garage cloud updates not supported
> [device] please post the above message in a github issue
> ```
> 
> Can you find these lines and post them here?

i can not find the given message in the logs.
my device is running with the local option.
![image](https://user-images.githubusercontent.com/87996039/127118120-6c01bffb-0708-42c4-85a5-45cf0310c44c.png)

**Comment by bwp91** [comment]
@app-ch ah no worries i assumed you were using cloud control 👍🏻

**Comment by rcoletti116** [comment]
beta ~~9~~ 10. MSL 120 not working locally (also not working w/ Cloud). Turns on and off, but color and white temperatures won't change. Device often goes unresponsive. Only error is:

[27/07/2021, 12:48:58] [Meross] [Bulb1] failed to refresh status as Cannot read property 'rgb2hs' of undefined at deviceLightbulb.requestUpdate (/usr/local/lib/node_modules/homebridge-meross/lib/device/lightbulb.js:493:57).

**Comment by bwp91** [comment]
> beta ~9~ 10. MSL 120 not working locally (also not working w/ Cloud). Turns on and off, but color and white temperatures won't change. Device often goes unresponsive. Only error is:
> 
> [27/07/2021, 12:48:58] [Meross] [Bulb1] failed to refresh status as Cannot read property 'rgb2hs' of undefined at deviceLightbulb.requestUpdate (/usr/local/lib/node_modules/homebridge-meross/lib/device/lightbulb.js:493:57).

Thanks, this should be fixed in beta 11

**Comment by rcoletti116** [comment]
> > beta ~9~ 10. MSL 120 not working locally (also not working w/ Cloud). Turns on and off, but color and white temperatures won't change. Device often goes unresponsive. Only error is:
> > [27/07/2021, 12:48:58] [Meross] [Bulb1] failed to refresh status as Cannot read property 'rgb2hs' of undefined at deviceLightbulb.requestUpdate (/usr/local/lib/node_modules/homebridge-meross/lib/device/lightbulb.js:493:57).
> 
> Thanks, this should be fixed in beta 11

Thanks. Looks like colors work now, but White Temperatures do not. 

If it will help, here are the payloads using HTTP Catcher for request for White and Color.
**White:**
`payload": {
    "light": {
      "rgb": -1,
      "capacity": 6,
      "channel": 0,
      "temperature": 88,
      "luminance": 100,
      "transform": -1
    }`

**Color**
`payload": {
    "light": {
      "rgb": 3080447,
      "capacity": 1,
      "channel": 0,
      "temperature": -1,
      "luminance": 100,
      "transform": -1
    }`

**Comment by bwp91** [comment]
Thanks, I think this should help, can you try beta 12?

**Comment by rcoletti116** [comment]
> Thanks, I think this should help, can you try beta 12?

still not quite there. It seems to have trouble switching between white and RGB values.
In debug I see RGB values actually sent when I request white.

`"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1627407674}],"triggerx":[],"timerx":[],"light":{"capacity":5,"channel":0,"rgb":16777215,"temperature":73,"luminance":100,"transform":-1}}}}}.**
[27/07/2021, 13:43:53] [Meross] [Bulb1] current brightness [100%].`

Could it be a conflict between the rgb value and temperature value?

**Comment by bwp91** [comment]
I've just released beta 13 with a few more checks for the lightbulb.

This data you have posted
```
"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1627407674}],"triggerx":[],"timerx":[],"light":{"capacity":5,"channel":0,"rgb":16777215,"temperature":73,"luminance":100,"transform":-1}}}}}.** [27/07/2021, 13:43:53] [Meross] [Bulb1] current brightness [100%].
```

Looks like an incoming update from meross, where it expresses an rgb value **and** a temperature value which I think is confusing the plugin.

There are two things to concentrate on here;

1. controlling through homekit, does it work ie does the device update to reflect what was commanded
2. controlling externally, do the homekit values update correctly if the device is controlled outside of homekit

Makes it easier for me to concentrate on the first and then the second.

**Comment by rcoletti116** [comment]
I'm not controlling outside of HomeKit. Those log lines were generated specifically when I used HomeKit.

**Comment by bwp91** [comment]
It must have come from polling then, the payload for sending device updates does not include the `"online":{"status":1}}`.

In the last couple of betas I have tried to mimic the payloads you provided earlier from http catcher.

Will get this sorted in the end!

**Comment by rcoletti116** [comment]
ok, same results on beta 13. To answer the above questions.

1. No, only when the bulb is on color. Changing between color and white causes issues.
2. Home does reflect the right color or temperature if I change it from Meross app. 

Regarding what you pointed out about the poll, what's interesting is when it is white, the RGB value is actually the last known color RGB value rather than the -1.

**Comment by AN1MATEK** [comment]
I have a MSS210 Plug and it's confirmed working with v6.0.0-beta.25.

`[28/07/2021, 11:43:58] [Meross] [test plug] sending mqtt: {"header":{"from":"/app/809344-bfcb1e8874172b27fe422b0eb8df9d08/subscribe","messageId":"5d0517887ce65a20ad86c8a3a05dec86","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"45211c5040d6fac9eab796a678d16840","timestamp":1627465439},"payload":{"togglex":{"channel":0,"onoff":1}}}.
[28/07/2021, 11:43:58] [Meross] [test plug] current state [on].
[28/07/2021, 11:43:58] [Meross] [test plug] incoming mqtt [Appliance.Control.ToggleX]: {"header":{"timestampMs":186,"timestamp":1627465439,"sign":"980f5f589f62bef58d328a40d14c8489","payloadVersion":1,"namespace":"Appliance.Control.ToggleX","method":"PUSH","messageId":"a0a6542ca42165d095e144d8e02a05f8","from":"/appliance/2009072899520751802748e1e92fe952/publish"},"payload":{"togglex":[{"onoff":1,"lmTime":1627465439,"channel":0}]}}.
[28/07/2021, 11:43:59] [Meross] [test plug] sending mqtt: {"header":{"from":"/app/809344-bfcb1e8874172b27fe422b0eb8df9d08/subscribe","messageId":"47a5d4dace4d7286b9f9d806d551f033","method":"SET","namespace":"Appliance.Control.ToggleX","payloadVersion":1,"sign":"1b26a6d62729e56a0f6ed2b6db728d38","timestamp":1627465440},"payload":{"togglex":{"channel":0,"onoff":0}}}.
[28/07/2021, 11:44:00] [Meross] [test plug] current state [off].
[28/07/2021, 11:44:00] [Meross] [test plug] incoming mqtt [Appliance.Control.ToggleX]: {"header":{"timestampMs":403,"timestamp":1627465440,"sign":"599795cb314d52975318d4f279197191","payloadVersion":1,"namespace":"Appliance.Control.ToggleX","method":"PUSH","messageId":"09c0275b21b50d329dd3129ba536de3d","from":"/appliance/2009072899520751802748e1e92fe952/publish"},"payload":{"togglex":[{"onoff":0,"lmTime":1627465440,"channel":0}]}}.`

**Comment by iMatux** [comment]
MOD100 local and online don't work, and plugin don't see it in "My Devices" tab.
MSS435E working local and online but can't separate channels even if specified 4, act as a single outlet turning on and off all the outlets.

**Comment by bwp91** [comment]
> MOD100 local and online don't work, and plugin don't see it in "My Devices" tab.
> MSS435E working local and online but can't separate channels even if specified 4, act as a single outlet turning on and off all the outlets.

Can you try 6.1.2-beta.0? Thanks

**Comment by iMatux** [comment]
> > MOD100 local and online don't work, and plugin don't see it in "My Devices" tab.
> > MSS435E working local and online but can't separate channels even if specified 4, act as a single outlet turning on and off all the outlets.
> 
> Can you try 6.1.2-beta.0? Thanks
Tried, first of all MSS310 is duplicated in Home app. MSS435E working like before with 4 channel separated, but locally I think there is a problem with polling cause there are all 4 channel on but Home shows only 2 are on.
Diffuser is now recognized, it shows on Home app but I can't control it. HomeBridge get the right commands like light or fan on/off but "Incoming Poll" has the same data, current light brightness is always [undefined%].
If you need logs let me know.

**Comment by iMatux** [comment]
> > MOD100 local and online don't work, and plugin don't see it in "My Devices" tab.
> > MSS435E working local and online but can't separate channels even if specified 4, act as a single outlet turning on and off all the outlets.
> 
> Can you try 6.1.2-beta.0? Thanks

Tried, first of all MSS310 is now duplicated in Home app. MSS435E working like before with 4 channel separated, but locally I think there is a problem with polling cause there are all 4 channel on but Home shows only 2 are on.
Diffuser is now recognized, it shows on Home app but I can't control it. HomeBridge get the right commands like light or fan on/off but "Incoming Poll" has the same data, current light brightness is always [undefined%].
If you need logs let me know.
P.S. Maybe a bug but not an error: Single outlet of MSS435E are marked as offline in dropdown list of "My Devices"

**Comment by bwp91** [comment]
@iMatux thanks

> MSS310 is now duplicated in Home app

Can you remove both from the accessory cache and see if the device gets re-added twice again?

> but locally I think there is a problem with polling

Can you get me a log entry of the polling data for your MSS435E

> "Incoming Poll" has the same data, current light brightness is always [undefined%]

I've fixed this logging issue, at the moment only the light is controllable for this device... hopefully... does controlling the light work through homebridge?

**Comment by iMatux** [comment]
> Can you remove both from the accessory cache and see if the device gets re-added twice again?
> 
Both removed, but one gets added even if deleted from config or UI plugin. My instance is only local.
> Can you get me a log entry of the polling data for your MSS435E
> 
Sure, this is the log:
`[30/7/2021, 10:48:01] [Meross] [Ciabatta] incoming poll: {"header":{"messageId":"kwpoo5w9lw61iyns","namespace":"Appliance.System.All","method":"GETACK","payloadVersion":1,"from":"/appliance/2005289830446890814248e1e91d837d/publish","timestamp":1627634881,"timestampMs":300,"sign":"93c3243dc979a86cc229c6ee3b8a742d"},"payload":{"all":{"system":{"hardware":{"type":"mss425e","subType":"eu","version":"3.0.0","chipType":"mt7682","uuid":"xxxxxxx","macAddress":"xxxxxxx"},"firmware":{"version":"3.1.8","compileTime":"2021/03/25 17:40:22 GMT +08:00","wifiMac":"xxxxx","innerIp":"192.168.1.90","server":"mqtt-eu.meross.com","port":443,"userId":xxxx},"time":{"timestamp":1627634881,"timezone":"Europe/Rome","timeRule":[[1603587600,3600,0],[1616893200,7200,1],[1635642000,3600,0],[1648342800,7200,1],[1667091600,3600,0],[1679792400,7200,1],[1698541200,3600,0],[1711846800,7200,1],[1729990800,3600,0],[1743296400,7200,1],[1761440400,3600,0],[1774746000,7200,1],[1792890000,3600,0],[1806195600,7200,1],[1824944400,3600,0],[1837645200,7200,1],[1856394000,3600,0],[1869094800,7200,1],[1887843600,3600,0],[1901149200,7200,1]]},"online":{"status":1}},"digest":{"togglex":[{"channel":0,"onoff":1,"lmTime":1627587825},{"channel":1,"onoff":1,"lmTime":1627634681},{"channel":2,"onoff":1,"lmTime":1627587825},{"channel":3,"onoff":1,"lmTime":1627587825},{"channel":4,"onoff":0,"lmTime":1627631755}],"triggerx":[],"timerx":[]}}}}.`
<img width="691" alt="Schermata 2021-07-30 alle 10 43 32" src="https://user-images.githubusercontent.com/23347512/127628265-800da44a-322d-4815-8004-099f137f3005.png">
<img width="693" alt="Schermata 2021-07-30 alle 10 43 24" src="https://user-images.githubusercontent.com/23347512/127628273-2b0071d6-f559-4e89-b722-2da2c8d84483.png">

> I've fixed this logging issue, at the moment only the light is controllable for this device... hopefully... does controlling the light work through homebridge?

Nope, even the light don't work, brightness nor color.

**Comment by bwp91** [comment]
@iMatux i don't suppose you are on the homebridge discord? to message on there?

I potentially have a lot of different questions depending on their answers and it's easier ping pong messaging than writing posts on here 😆

**Comment by iMatux** [comment]
@bwp91 Nope, I don't use Discord that much but I can join now.

**Comment by pidster** [comment]
Hi. On v6.1.1 my MSS420F is being found, but only shows as a single switch/outlet, should be a master switch + 4 channels.

**Comment by bwp91** [comment]
@pidster thanks, this should be fixed in newest beta version of the plugin

**Comment by jhives82** [comment]
If you add MSL320M to constants for lightRGB it immediately gets picked up and functions:

./utils/constants.js:    lightRGB: ['MSL120', 'MSL120B', 'MSL120D', 'MSL320', 'MSL320M', 'MSL420', 'MSL430'],

**Comment by bwp91** [comment]
> If you add MSL320M to constants for lightRGB it immediately gets picked up and functions:
> 
> ./utils/constants.js: lightRGB: ['MSL120', 'MSL120B', 'MSL120D', 'MSL320', 'MSL320M', 'MSL420', 'MSL430'],

Thanks for this! Just released a beta, v6.2.1-beta.1, with this change.

**Comment by ctkidd78** [comment]
MSG200 is working fine but I can't turn off the closing alarm. I have it off in the app but no matter how I connect the plugin (cloud or local) it still sounds the alarm when closing. Any chance of adding an option to the plugin to control this? I leave really early in the morning and don't want to wake up the neighbors lol.

**Comment by bwp91** [comment]
> MSG200 is working fine but I can't turn off the closing alarm. I have it off in the app but no matter how I connect the plugin (cloud or local) it still sounds the alarm when closing. Any chance of adding an option to the plugin to control this? I leave really early in the morning and don't want to wake up the neighbors lol.

Hi @ctkidd78 

Can you put the plugin in debug mode and restart. Then get the logs when accessory initialises you should see an entry like `incoming data` with a load of info. Also if you control garage from meross app you should see a log entry appear like `incoming mqtt`.

Can you get me these logs?

Thanks

**Comment by ctkidd78** [comment]
> > MSG200 is working fine but I can't turn off the closing alarm. I have it off in the app but no matter how I connect the plugin (cloud or local) it still sounds the alarm when closing. Any chance of adding an option to the plugin to control this? I leave really early in the morning and don't want to wake up the neighbors lol.
> 
> Hi @ctkidd78
> 
> Can you put the plugin in debug mode and restart. Then get the logs when accessory initialises you should see an entry like `incoming data` with a load of info. Also if you control garage from meross app you should see a log entry appear like `incoming mqtt`.
> 
> Can you get me these logs?
> 
> Thanks

Sorry for the delay. Here is what my log is looking like when restarted. I removed the serial numbers, mac address and such but they show just fine.

[8/2/2021, 9:55:57 PM] [Meross] [Smart Garage Door Opener] sending update: {"header":{"from":"http://192.168.1.232/config","messageId":"","method":"GET","namespace":"Appliance.System.All","payloadVersion":1,"sign":"","timestamp":1627955757,"triggerSrc":"iOSLocal","uuid":""},"payload":{}}.
[8/2/2021, 9:55:57 PM] [Meross] [Smart Garage Door Opener] initialised with id [] [local].
[8/2/2021, 9:55:57 PM] [Meross] ✓ Setup complete.

[8/2/2021, 9:55:57 PM] [Meross] [Smart Garage Door Opener] incoming poll: {"header":{"messageId":"","namespace":"Appliance.System.All","triggerSrc":"iOSLocal","method":"GETACK","payloadVersion":1,"from":"/appliance//publish","timestamp":1627955758,"timestampMs":808,"sign":""},"payload":{"all":{"system":{"hardware":{"type":"msg200","subType":"us","version":"2.0.0","chipType":"mt7682","uuid":"","macAddress":""},"firmware":{"version":"2.1.3","compileTime":"2020/04/17 11:58:10 GMT +08:00","wifiMac":"","innerIp":"192.168.1.232","server":"mqtt-us.meross.com","port":443,"userId":},"time":{"timestamp":1627955758,"timezone":"America/Puerto_Rico","timeRule":[[-1,-14400,0]]},"online":{"status":1}},"digest":{"triggerx":[{"channel":1,"id":"2222222222222222","count":2},{"channel":2,"id":"3333333333333333","count":1},{"channel":3,"id":"4444444444444444","count":1}],"timerx":[],"garageDoor":[{"channel":1,"doorEnable":1,"open":0,"lmTime":1627954875},{"channel":2,"doorEnable":0,"open":1,"lmTime":0},{"channel":3,"doorEnable":0,"open":1,"lmTime":0}]}}}}.

**Comment by bwp91** [comment]
@ctkidd78 

did you ever use http catcher (or charles proxy) to setup this plugin before v6? Like to get the messageId and other data for devices?

If so, could you control the garage from the meross app on your phone and get the full payload from the httpcatcher app that was sent?

Otherwise, could you put the device into cloud mode (by removing the IP from the plugin config), then control the garage from the meross app, and get the `incoming mqtt` message that will appear in the logs?

**Comment by AN1MATEK** [comment]
I'd like to give my thanks for the active development brought to this plugin.

Could the MRS100 ever support stateful switches or eventually work like a Homekit supported roller shutter? Or the do not communicate anything back?

As for now, I have to manually do a scrip to stop it a 50% after X seconds. It works well, but there is place for improvement. 

Cheers :)

**Comment by bwp91** [comment]
> I'd like to give my thanks for the active development brought to this plugin.
> 
> Could the MRS100 ever support stateful switches or eventually work like a Homekit supported roller shutter? Or the do not communicate anything back?
> 
> As for now, I have to manually do a scrip to stop it a 50% after X seconds. It works well, but there is place for improvement.
> 
> Cheers :)

The current implementation of stateless buttons is the 'safest' (and yes, easiest!) approach that works for both cloud and local mode. There's not much that can go wrong.

I'm still not entirely sure on the exact protocol for these devices, through old issue digging I have seen sometimes it reports a state (like 0, 1, 2, 3?) to the plugin, and other times a position (like 0, 100, never in between). Without owning this model for testing, or without remote access to one with a meross account, it is difficult to get an understand of exactly what the device reports to the plugin, and when, and even when it doesn't.

> Could the MRS100 ever support stateful switches

The stateful buttons could work, but maybe wouldn't be reliable in local mode. If the device is controlled outside of homebridge, and due to the polling, there may be a delay between the buttons turning on/off. Or even not at all, e.g. if the polling is set at 60 seconds, at 20 seconds in the roller is opened, stopped 10 seconds later, then the plugin would never have even realised that the roller had moved.

> or eventually work like a Homekit supported roller shutter?

The device doesn't seem to report its current location % to the plugin, and without this info implementing this accessory type is a real challenge. Theoretically possible (calculating needed times to turn on/off from current %, new % and a defined operation time), but not reliable when real-time communication isn't possible. The % shown in home app may stay accurate if the device is only ever controlled from homebridge... but would get out of sync if the device is controlled externally. and even worse with local polling. And if it does get out of sync, there is no easy way of getting back into sync (if you change the % in home app, the device will just move again).

If and when Meross allow for %-based control, ideally the ability to send a new % to move to, and the device reporting to the plugin the current-% if it changes, then a roller accessory would be much safer to implement. It appears to be something they say on their website is coming in the future.

**Comment by pixsterfr** [comment]
Hi, i have 4 MSS710 and no one show up in the v6. Thanks for your work !

**Comment by bwp91** [comment]
> Hi, i have 4 MSS710 and no one show up in the v6. Thanks for your work !

can you post your meross config? obfuscate any email/password/userkey you have set... i can't tell whether you have them configured in the first place if you remove them totally!

**Comment by AN1MATEK** [comment]
> Without owning this model for testing, or without remote access to one with a meross account, it is difficult to get an understand of exactly what the device reports to the plugin, and when, and even when it doesn't.

I can definitely send one your way if you want. They only sold a pair and I needed one. Would you like that?

**Comment by GazzaPr** [comment]
Any timeframe for the MSL-100 and MSS-420F support?

**Comment by bwp91** [comment]
> Any timeframe for the MSL-100 and MSS-420F support?

Maybe they work already. have you tried?

**Comment by GazzaPr** [comment]
Not tried the latest but previously the MAL didn’t show and the 420 showed as 1 point rather than the 4. Away for a couple of days but will try when I get back

**Comment by bwp91** [comment]
> Not tried the latest but previously the MAL didn’t show and the 420 showed as 1 point rather than the 4. Away for a couple of days but will try when I get back
> […](#)

Yes these two devices should work already. The MSL100 as a dimmer light and the MSS420 actually as 5 switches in homebridge, the plugin will create a switch for each channel + an 'all on/off switch'. You can hide any of the accessories that are created via the config.

**Comment by bwp91** [comment]
> > Without owning this model for testing, or without remote access to one with a meross account, it is difficult to get an understand of exactly what the device reports to the plugin, and when, and even when it doesn't.
> 
> I can definitely send one your way if you want. They only sold a pair and I needed one. Would you like that?

@facundo59 are you on the homebridge discord channel at all?

**Comment by GazzaPr** [comment]
Hi Ben,
the 420F is now showing.  I decided to start again and deleted the whole Meross configuration and all the majority of the devices have shown up as cloud and therefore no further config is required (apart from name changes).

The only issue I now have is that I can't "find" the MSL100 bulbs either as cloud or local.  

When I input as local I get a "WARNING Config entry [lightDevices] has an invalid entry which will be ignored." message.

the basic config is:
"lightDevices": [
                {
                    "name": "Bedroom",
                    "deviceUrl": "192.168.2.7",
                    "model": "MSL-100D",
                    "brightnessStep": 5,
                    "firmwareRevision": "3.1.1"
\
I suspect(?)  that the model is the issue as there is only  the choice of MSL-100 or MSL100-D (I have tried both choices with the same result) rather than the MSL100-r that the meross app reports.
Many thanks for all your help

**Comment by bwp91** [comment]
Hi @GazzaPr 

If you update to the beta version, at least 6.5.1-beta.14, I have added an option for this MSL100R so you can set the `model` to `MSL100R`.

The plugin is complaining because you have missed the `serialNumber` property in the `lightDevices[]`. This is the 32 digit number that is displayed in the log when the plugin loads, or indeed in the plugin-ui in the 'My Devices' tab.

```json
"lightDevices": [
  {
    "name": "Bedroom",
    "serialNumber": "2009%%%%%%%%...",
    "deviceUrl": "192.168.2.7",
    "model": "MSL100R",
    "brightnessStep": 5,
    "firmwareRevision": "3.1.1"
  }
]
```

The serial number is needed so the plugin knows to apply that block of config to that specific device. I can't rely on the `deviceUrl` to link config <-> device in the very small chance that two devices swap IPs on the network!

**Comment by GazzaPr** [comment]
Thanks Ben,

Works perfectly 😀👍

Gary

Out and about so limited access.

**Comment by neversettledwanderer** [comment]
Hi Ben, 

MSS420F works fine with the cloud setup, the smart switch with individual switch show up in the plugin as normal and work fine as well.

**Comment by bwp91** [comment]
> Hi Ben,
> 
> MSS420F works fine with the cloud setup, the smart switch with individual switch show up in the plugin as normal and work fine as well.

thanks, good to know - i’ve updated the wiki!

**Comment by Ruben-Denolf** [comment]
MSS120B working locally, have not tried cloud.

**Comment by pidster** [comment]
> @pidster thanks, this should be fixed in newest beta version of the plugin

@bwp91 Confirm this is fixed (am on 6.7.2). Appreciate all the hard work!

**Comment by bwp91** [comment]
@Ruben-Denolf thanks, i've updated wiki!

@pidster thanks!

**Comment by RZr0967** [comment]
Hi,

please add MSL320CP Light Stripe.

Many thanks for your work!

**Comment by bwp91** [comment]
> Hi,
> 
> please add MSL320CP Light Stripe.
> 
> Many thanks for your work!

MSL320CP should work in the latest beta, 6.8.1-beta.1 :)

**Comment by Tongo91** [comment]
Hi thanks for the work so far, I would love to see the mts100 (smart valves) working using a msh300 as a hub for them.

**Comment by Leftibus** [comment]
Thanks for the stead updates so far.  I am facing an issue with MSS110 outlets which are native HomeKit.  They are now showing twice in home app.  I have checked "ignore HomeKit native devices" in configuration but this doesn't seem to work.

**Comment by bwp91** [comment]
> Thanks for the stead updates so far. I am facing an issue with MSS110 outlets which are native HomeKit. They are now showing twice in home app. I have checked "ignore HomeKit native devices" in configuration but this doesn't seem to work.

Hi, which hardware version of the MSS110 do you own?

**Comment by Leftibus** [comment]
> > Thanks for the stead updates so far. I am facing an issue with MSS110 outlets which are native HomeKit. They are now showing twice in home app. I have checked "ignore HomeKit native devices" in configuration but this doesn't seem to work.
> 
> 
> 
> Hi, which hardware version of the MSS110 do you own?

Not sure how to check?

Also, it seems all of my native HomeKit meross devices are showing twice in home app :(

**Comment by Leftibus** [comment]
> > > Thanks for the stead updates so far. I am facing an issue with MSS110 outlets which are native HomeKit. They are now showing twice in home app. I have checked "ignore HomeKit native devices" in configuration but this doesn't seem to work.
> > 
> > 
> > 
> > Hi, which hardware version of the MSS110 do you own?
> 
> Not sure how to check?
> 
> Also, it seems all of my native HomeKit meross devices are showing twice in home app :(

So the hardware version that shows in the meross app is 4.0.0

**Comment by cossyg** [comment]
Hi, thanks for all your work. Is the msh100 hub and it’s sub devices actually a supported device? They don’t show up as my devices in homebridge but they are in the supported  list

**Comment by cossyg** [comment]
Also native HomeKit  Uk plugs mss210 are showing up in the plug-in, hardware version 4.0.0

**Comment by lightsquall** [comment]
Hi.
Would you please support MSL210 ceiling fixtures

Thanx in advance.

[Room Light] is currently not supported, do create a github issue https://git.io/JtfVC with info:
{"uuid":"2105289454932390851648e1e971f683","onlineStatus":1,"devName":"Room Light","devIconId":"device_msl210_jp","bindTime":1630313042,"deviceType":"msl210","subType":"jp","channels":[{}],"region":"ap","fmwareVersion":"2.2.1","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-ap-2.meross.com","reservedDomain":"mqtt-ap-2.meross.com","firmware":"2.2.1","hbDeviceId":"2105289454932390851648e1e971f683","model":"MSL210"}

**Comment by bwp91** [comment]
@lightsquall please install the newest beta version of the plugin v6.10.1-beta.0.

The MSL210 should then appear in Homebridge... controlling it may or may not work depending on whether the plugin code is correct... let me know how you get on!

**Comment by bwp91** [comment]
> Hi, thanks for all your work. Is the msh100 hub and it’s sub devices actually a supported device? They don’t show up as my devices in homebridge but they are in the supported list

At this time, the only supported hub and subdevice is the MSH300 with the MS100 sensors. If you have a different device I can look into implementing it... the MTS100 is on my to-do list at some point!

**Comment by bwp91** [comment]
> Also, it seems all of my native HomeKit meross devices are showing twice in home app :(

@Leftibus can you get me a list of the homekit native models you own along with their hardware versions? This info can be seen in the plugin settings, under the 'My Devices' tab.

I know you mentioned the MSS110 with hardware version 4, is this the full model number? I'm asking as there are sometimes extra letters after the 'base' model version like MSS110R. The 'model' in the 'My Devices' tab will show the full model.

**Comment by cossyg** [comment]
> > Hi, thanks for all your work. Is the msh100 hub and it’s sub devices actually a supported device? They don’t show up as my devices in homebridge but they are in the supported list
> 
> At this time, the only supported hub and subdevice is the MSH300 with the MS100 sensors. If you have a different device I can look into implementing it... the MTS100 is on my to-do list at some point!

Thanks, yes sorry got my model numbers mixed up - I have the MSH300 with the MTS100 valves, so I assume they won't show up yet?

**Comment by bwp91** [comment]
@cossyg your MTS100 valves should appear and work in the new version of the plugin. If your valves have a different model number to `MTS100V3` let me know as I may need to make a couple of additions.

**Comment by cossyg** [comment]
Thank you so much, that is amazing. Seemed to all work very easily, I'll
report back on any issues

**Comment by bwp91** [comment]
@cossyg  not sure if you use the Eve HomeKit app, but there is more functionality via this app, you can see a graph of the current temperature, set to the different modes and the status of the 'open window' feature:

![image0](https://user-images.githubusercontent.com/43026681/132670637-40c35009-7105-41ed-83ac-e38c2b91bacd.png)

**Comment by atlienk** [comment]
Is support for the Air Purifier (MAP100) coming anytime soon?

**Comment by bwp91** [comment]
> Is support for the Air Purifier (MAP100) coming anytime soon?

New models can be added when requested and if you are happy to work with me to get them working :)

**Comment by atlienk** [comment]
I can try to offer my help, but I'm not a developer. I can definitely be a tester though.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bwp91** [comment]
> I can try to offer my help, but I'm not a developer. I can definitely be a tester though. Sent with [ProtonMail](https://protonmail.com/) Secure Email. ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> […](#)

No problem, it's just copying things from the homebridge log as I ask for them :) and it's much easier if we can message on discord:

https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
@atlienk i have sent you a dm on discord

**Comment by atlienk** [comment]
I'm having issues with discord at the moment. I don't use it very much and it seems to have changed my email address or phone number. I'll get back to you when i get that sorted.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by nastypenman** [comment]
@bwp91 Thanks Ben for the great work.

I have a 6-outlet MSS426S (older version which doesn't support HomeKit).  Is there any chance that can be added to the supported list?  Log attached below, please let me know what I can do to help.

[28/09/2021, 12:37:56] [Meross] [Dining Room Meross] is not supported, do create a github issue https://bit.ly/hb-meross-issues with info:
{"uuid":"edited","onlineStatus":1,"devName":"Dining Room Meross","devIconId":"device034_uk","bindTime":1572262575,"deviceType":"mss426s","subType":"uk","channels":[{},{"type":"Switch","devName":"Backlight","devIconId":"device001"},{"type":"Switch","devName":"Top Light","devIconId":"device001"},{"type":"Switch","devName":"Right Light","devIconId":"device001"},{"type":"Switch","devName":"Filter","devIconId":"device001"},{"type":"Switch","devName":"Fish Doctor","devIconId":"device001"},{"type":"Switch","devName":"Spare Socket","devIconId":"device001"},{"type":"USB","devName":"USB","devIconId":"device001"}],"region":"ap","fmwareVersion":"2.1.5","hdwareVersion":"2.0.0","userDevIcon":"","iconType":1,"skillNumber":"","cluster":2,"domain":"mqtt-ap-2.meross.com","reservedDomain":"mqtt-ap-2.meross.com","firmware":"2.1.5","hbDeviceId":"edited","model":"MSS426S"}

**Comment by bwp91** [comment]
Hi @nastypenman if you update to the beta version 6.12.1-beta.3, this device should start working straight away...

https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

**Comment by lightsquall** [comment]
> @lightsquall please install the newest beta version of the plugin v6.10.1-beta.0.
> 
> The MSL210 should then appear in Homebridge... controlling it may or may not work depending on whether the plugin code is correct... let me know how you get on!

hi.
MSL210 works fine w/ mentioned beta and latest release.
Thanks for your great work.

**Comment by nastypenman** [comment]
> Hi @nastypenman if you update to the beta version 6.12.1-beta.3, this device should start working straight away...
> 
> https://github.com/bwp91/homebridge-meross/wiki/Beta-Version

OMG it works like a charm.  Thanks, you are the best.

**Comment by bwp91** [comment]
> > Hi @nastypenman if you update to the beta version 6.12.1-beta.3, this device should start working straight away...
> > https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
> 
> OMG it works like a charm. Thanks, you are the best.

I've just realised in fact this device effectively has 7 outlets? the six standard and another to turn on/off the usb ports?

**Comment by luismsousa** [comment]
> > > Hi @nastypenman if you update to the beta version 6.12.1-beta.3, this device should start working straight away...
> > > https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
> > 
> > 
> > OMG it works like a charm. Thanks, you are the best.
> 
> I've just realised in fact this device effectively has 7 outlets? the six standard and another to turn on/off the usb ports?

@nastypenman is yours the model mss426 or mss426s? 
I have a model mss426 that also isn’t recognised. Just wanted to confirm it’s the same. I’ll try the beta tomorrow anyway.

**Comment by bwp91** [comment]
> > > > Hi @nastypenman if you update to the beta version 6.12.1-beta.3, this device should start working straight away...
> > > > https://github.com/bwp91/homebridge-meross/wiki/Beta-Version
> > > 
> > > 
> > > OMG it works like a charm. Thanks, you are the best.
> > 
> > 
> > I've just realised in fact this device effectively has 7 outlets? the six standard and another to turn on/off the usb ports?
> 
> @nastypenman is yours the model mss426 or mss426s? I have a model mss426 that also isn’t recognised. Just wanted to confirm it’s the same. I’ll try the beta tomorrow anyway.

Which is the exact model number?

**Comment by luismsousa** [comment]
> 
> Which is the exact model number?

@bwp91 I've pulled this from the homebridge logs:
```
{
    "onlineStatus": 1,
    "deviceType": "mss426",
    "subType": "uk",
    "channels": [
        {},
        {
            "type": "Switch",
            "devName": "Switch 1",
            "devIconId": "device001"
        },
        {
            "type": "Switch",
            "devName": "Switch 2",
            "devIconId": "device001"
        },
        {
            "type": "Switch",
            "devName": "Switch 3",
            "devIconId": "device001"
        },
        {
            "type": "Switch",
            "devName": "Switch 4",
            "devIconId": "device001"
        },
        {
            "type": "Switch",
            "devName": "Switch 5",
            "devIconId": "device001"
        },
        {
            "type": "Switch",
            "devName": "Switch 6",
            "devIconId": "device001"
        },
        {
            "type": "USB",
            "devName": "USB",
            "devIconId": "device001"
        }
    ],
    "region": "eu",
    "fmwareVersion": "6.1.2",
    "hdwareVersion": "6.0.0",
    "userDevIcon": "",
    "iconType": 1,
    "skillNumber": "",
    "cluster": 1,
    "domain": "mqtt-eu.meross.com",
    "reservedDomain": "mqtt-eu.meross.com",
    "firmware": "6.1.2",
    "model": "MSS426"
}
```

From the app's perspective, it has 8 switches, a main global switch, 6 plug switches, and a USB switch
![File](https://user-images.githubusercontent.com/1799045/136181401-a75fa355-1f20-453d-a192-a646e6895b0b.jpg)
.

**Comment by bwp91** [comment]
Hi @luismsousa 

This MSS426 should work in the beta version of the plugin, v7.0.0-beta.7. It should show as 8 devices (you can hide any of them with the plugin config).
