### ISSUE TITLE
NaN for Temperature, Humidity and Battery Level from MS100EU

### ISSUE THREAD

**Issue by Tongo91** [donavanbecker/homebridge-meross#476]
Hello and happy new year.
I get a lot of "NaN" Errors from my Temperature and Humidity Sensors that are working over the MSH300 hub (Firmware 4.1.35 and hardware 4.0.0) 
Sometimes I get less and sometimes a lot more of them, is there any reason for those Errors? In the Meross App itself everything looks normal. 

Here are some Logs:
[02/01/2023, 16:12:53] [homebridge-meross] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[02/01/2023, 16:22:52] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[02/01/2023, 16:22:52] [Meross] [Kellersensor] current temperature [NaN°C].
[02/01/2023, 16:22:52] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[02/01/2023, 16:22:52] [Meross] [Kellersensor] current humidity [NaN%].
[02/01/2023, 16:22:52] [homebridge-meross] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[02/01/2023, 16:27:52] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.

**Comment by bwp91** [comment]
Hi @Tongo91 

Can you update to the beta version of the plugin and show me this logging again? you should see more red entries this time (they are not actually errors).

I need to be able to see these red entries.

Thanks!

**Comment by Tongo91** [comment]
Hi, thanks for the fast reply, I did the update now and waiting for the NaN Error.
Currently everything is reporting normal since a few hours, as I said above sometimes it works and then I get those errors over a few hours. 

I will update as soon as I see the NaN Logs again including the red entries then :)

**Comment by Tongo91** [comment]
[04/01/2023, 07:04:11] [Meross] {"id":"120027D2980F","status":1,"onoff":0,"lastActiveTime":1672812104,"ms100":{"latestTime":1672812104,"latestTemperature":139,"latestHumidity":810,"voltage":2862}}
[04/01/2023, 07:04:11] [Meross] {"id":"120027D23B71","status":1,"onoff":0,"lastActiveTime":1672812196,"ms100":{"latestTime":1672812196,"latestTemperature":102,"latestHumidity":670,"voltage":2716}}
[04/01/2023, 07:04:11] [Meross] {"id":"120027D22FF1","status":2}
[04/01/2023, 07:09:11] [Meross] {"id":"120027D2980F","status":1,"onoff":0,"lastActiveTime":1672812413,"ms100":{"latestTime":1672812413,"latestTemperature":139,"latestHumidity":810,"voltage":2862}}
[04/01/2023, 07:09:11] [Meross] {"id":"120027D23B71","status":1,"onoff":0,"lastActiveTime":1672812484,"ms100":{"latestTime":1672812484,"latestTemperature":102,"latestHumidity":670,"voltage":2716}}
[04/01/2023, 07:09:11] [Meross] {"id":"120027D22FF1","status":1,"onoff":0,"lastActiveTime":1672812257,"ms100":{"latestTime":1672812257}}
[04/01/2023, 07:09:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:09:11] [Meross] [Schlafzimmer] current temperature [NaN°C].
[04/01/2023, 07:09:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:09:11] [Meross] [Schlafzimmer] current humidity [NaN%].
[04/01/2023, 07:09:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:14:11] [Meross] {"id":"120027D2980F","status":1,"onoff":0,"lastActiveTime":1672812722,"ms100":{"latestTime":1672812722,"latestTemperature":139,"latestHumidity":810,"voltage":2862}}
[04/01/2023, 07:14:11] [Meross] {"id":"120027D23B71","status":1,"onoff":0,"lastActiveTime":1672812773,"ms100":{"latestTime":1672812773,"latestTemperature":102,"latestHumidity":670,"voltage":2716}}
[04/01/2023, 07:14:11] [Meross] {"id":"120027D22FF1","status":1,"onoff":0,"lastActiveTime":1672812257,"ms100":{"latestTime":1672812257}}
[04/01/2023, 07:14:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:14:11] [Meross] [Schlafzimmer] current temperature [NaN°C].
[04/01/2023, 07:14:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:14:11] [Meross] [Schlafzimmer] current humidity [NaN%].
[04/01/2023, 07:14:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:19:11] [Meross] {"id":"120027D2980F","status":1,"onoff":0,"lastActiveTime":1672813031,"ms100":{"latestTime":1672813031,"latestTemperature":139,"latestHumidity":810,"voltage":2862}}
[04/01/2023, 07:19:11] [Meross] {"id":"120027D23B71","status":1,"onoff":0,"lastActiveTime":1672813062,"ms100":{"latestTime":1672813062,"latestTemperature":102,"latestHumidity":670,"voltage":2716}}
[04/01/2023, 07:19:11] [Meross] {"id":"120027D22FF1","status":1,"onoff":0,"lastActiveTime":1672812257,"ms100":{"latestTime":1672812257}}
[04/01/2023, 07:19:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:19:11] [Meross] [Schlafzimmer] current temperature [NaN°C].
[04/01/2023, 07:19:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Current Relative Humidity': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.
[04/01/2023, 07:19:11] [Meross] [Schlafzimmer] current humidity [NaN%].
[04/01/2023, 07:19:11] [homebridge-meross] This plugin generated a warning from the characteristic 'Battery Level': characteristic value expected valid finite number and received "NaN" (number). See https://homebridge.io/w/JtMGR for more info.


Here are the latest logs with the red entries around the NaN Errors, I hope that helps.

**Comment by Tongo91** [comment]
Hi @bwp91 do you need any further information?

**Comment by Tongo91** [comment]
I will revert my version for the stable version now, to clean up my logs and stop the excessive logging.
If you need any further information, I am ready for updating to the beta again.

**Comment by bwp91** [comment]
Hi @Tongo91 

sorry the delay in replying. thanks for the logs - please check the latest version of the plugin i have just released :)

**Comment by Tongo91** [comment]
Hi @bwp91 

no problem, thank you for looking into it. 
I updated my version now, thank you.

**Comment by bwp91** [comment]
please let me know if you see any more messages like this. i’m starting to doubt my fix now 😅

**Comment by Tongo91** [comment]
You are right 😂 I just checked the logs right now and the NaN message still exists. ![image](https://user-images.githubusercontent.com/90055492/213777497-bb57565c-f476-4cc0-b36f-9db30e623232.png)

**Comment by bwp91** [comment]
Newest version should properly fix this now!

**Comment by Tongo91** [comment]
Hi @bwp91,

looks good, I can't see any NaN errors anymore. 
But the red additional logging is still active, maybe you should disable that again for the stable version? 

Thanks a lot for the ongoing great work!

**Comment by bwp91** [comment]
You are correct - sorry - forget these things when I don't own the device myself. Please see newest version!

**Comment by Tongo91** [comment]
That worked and no more errors. Thank you!

**Comment by bwp91** [comment]
Amazing! thanks for reporting this 👍
